name: Run Deno Tests

on:
    push:
        branches: [master, main]
    pull_request:
        branches: [master, main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Install Deno
              uses: denoland/setup-deno@v1
              with:
                deno-version: latest

            - name: Cache dependencies
              run: deno cache main.ts

            - name: Run Deno tests
              run: deno test